name: mcdeanstudios
favicon: null
layout_spectrum: 0.99697
typography_spectrum: 0.5920784929767251
title: MC Dean Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdad6'
    - '#fe6a24'
    - '#242227'
    - '#40acae'
    - '#58637f'
  brandStrength: 0.19238824071362615
  lightness: 0.8250081688165665
  saturation: 0.7479005826171488
  rhythmicContrast: 0.7609584573656321
purpose: []
