name: mcdeanstudios
favicon: null
layout_spectrum: 0.5184994300361723
typography_spectrum: 0.5920784929767251
title: MC Dean Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.19238824071362615
  lightness: 0.8250081688165665
  saturation: 0.7479005826171488
  rhythmicContrast: 0.7609584573656321
purpose: []
